title: Tech - Tips, Tricks, & Tutorials
site-name: sTechalon.com
sub-title: Sharing My Experience
description: Hi, I am Alon Shrestha owner of this website and I am sharing my experience and interest on Tech.
author: Alon Shrestha
aurl: https://alonshrestha.com.np
about: Hi, I am Alon Shrestha.
disqus_shortname: stechalon
google_analytics: UA-168921521-1
enableTags: true
tagarray: []

collections:
  project:
    output: true
    
    
permalink: /:title

social: 
    - icon: fa-instagram
      link: "https://www.instagram.com/a.l_o.n/"
    - icon: fa-twitter
      link: "https://twitter.com/stechalon"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/alonshrestha/"
    - icon: fa-github
      link: "https://github.com/alonshrestha/"

share:
  twitter_username: stechalon
  fb_appid: 
   # Navigation
urls:
    - text: Web Hosting
      url: /category/webhosting
    - text: Linux
      url: /category/linux
    - text: Know Me
      url: /about
      # - text: My Projects
    #   url: /projects/
    # - text: XML Feed
    #   url: /feed.xml

url: "https://stechalon.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
