title: Tech - Tips, Tricks, & Tutorials | sTechalon.com
sub-title: Sharing My Experience
description: A guy from Nepal sharing his experience on Tech. Articles and tutorials about System and Network, SEO, Social Media, Web Hosting, Servers, and others.
author: sTechalon.com
aurl: https://alonshrestha.com.np
about: A computer science student.
disqus_shortname: stechalon
google_analytics: UA-168921521-1
enableTags: true
tagarray: []

collections:
  project:
    output: true
    
    
permalink: /:title

social: 
    - icon: fa-instagram
      link: "https://www.instagram.com/a.l_o.n/"
    - icon: fa-twitter
      link: "https://twitter.com/stechalon"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/alonshrestha/"
    - icon: fa-github
      link: "https://github.com/alonshrestha/"

share:
  twitter_username: stechalon
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://stechalon.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
